name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "frontend/"
          target: "~/apps/fishies/frontend"

      - name: Copy backend to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "backend/"
          target: "~/apps/fishies/backend"

      - name: Execute deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            ### FRONTEND
            cd ~/apps/fishies/frontend
            npm install
            npm run build

            pm2 restart fishies-frontend || pm2 start npm --name fishies-frontend -- run start


            ### BACKEND
            cd ~/apps/fishies/backend
            npm install
            npx prisma migrate deploy

            pm2 restart fishies-backend || pm2 start npm --name fishies-backend -- run start:prod

            pm2 save
